create extension if not exists pgcrypto;

create table if not exists public.interests (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  preferred_name text not null default '',
  email text not null check (email = lower(email)),
  phone text not null,
  city text not null,
  state text not null,
  institution text not null,
  institution_type text not null,
  field_of_study text not null default '',
  graduation_year text not null default '',
  current_status text not null,
  chapter_interest text not null,
  why_interested text not null,
  brotherhood_meaning text not null,
  referral_source text not null default '',
  status text not null default 'new'
    check (status in ('new', 'under_review', 'interview', 'accepted', 'declined', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_interests_status_created_at
  on public.interests (status, created_at desc);
create index if not exists idx_interests_email
  on public.interests (lower(email));

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  email text not null unique check (email = lower(email)),
  full_name text not null,
  user_id uuid,
  role text not null default 'brother'
    check (role in ('super_admin', 'national_officer', 'chapter_officer', 'brother', 'alumni', 'applicant')),
  title text not null default '',
  chapter text not null default '',
  location text not null default '',
  bio text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_members_email_unique
  on public.members (email);
create index if not exists idx_members_active_chapter
  on public.members (active, chapter);
create index if not exists idx_members_role_active
  on public.members (role, active);

create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  audience text not null default 'all',
  author_member_id bigint not null references public.members(id) on delete restrict,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_announcements_published_created_at
  on public.announcements (published, created_at desc);
create index if not exists idx_announcements_audience_created_at
  on public.announcements (audience, created_at desc);

create table if not exists public.discussion_threads (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  category text not null default 'brotherhood'
    check (category in ('brotherhood', 'chapter', 'service', 'scholarship', 'events', 'history')),
  author_member_id bigint not null references public.members(id) on delete restrict,
  pinned boolean not null default false,
  locked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_discussion_threads_pinned_created_at
  on public.discussion_threads (pinned desc, updated_at desc);
create index if not exists idx_discussion_threads_author_member_id
  on public.discussion_threads (author_member_id);

create table if not exists public.discussion_replies (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.discussion_threads(id) on delete cascade,
  author_member_id bigint not null references public.members(id) on delete restrict,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_discussion_replies_thread_created_at
  on public.discussion_replies (thread_id, created_at);

alter table public.interests enable row level security;
alter table public.members enable row level security;
alter table public.announcements enable row level security;
alter table public.discussion_threads enable row level security;
alter table public.discussion_replies enable row level security;

revoke all on table public.interests from anon, authenticated;
revoke all on table public.members from anon, authenticated;
revoke all on table public.announcements from anon, authenticated;
revoke all on table public.discussion_threads from anon, authenticated;
revoke all on table public.discussion_replies from anon, authenticated;

grant select, insert, update, delete on table public.interests to service_role;
grant select, insert, update, delete on table public.members to service_role;
grant select, insert, update, delete on table public.announcements to service_role;
grant select, insert, update, delete on table public.discussion_threads to service_role;
grant select, insert, update, delete on table public.discussion_replies to service_role;
grant usage, select on sequence public.members_id_seq to service_role;
